### ISSUE TITLE
Why route() configuration is not supported for runner?

### ISSUE THREAD

**Issue by terasaka2k** [Strider-CD/strider-extension-loader#11]
Would someone explain why `route(app, context)` configuration is not supported for runner plugins?

I need per-branch namespaced routes so that I can provide a simple REST API for my runner config page which relies on branch configurations.

**Comment by knownasilya** [comment]
Not really sure, but according to the readme

> Runner plugins do not get loaded in the worker environment.

That would probably do it, since routes are configured in the worker.

**Comment by terasaka2k** [comment]
Thank you for reply.

However I have forgotten the details of what I did, it's not technically hard to support the feature if I remember correctly.

I will investigate the reason someday.
